[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }


[[redirects]]
    from="/api/*"
    to="/.netlify/functions/:splat"
    status=200
    
